### ISSUE TITLE
1918 reference is a red herring

### ISSUE THREAD

**Issue by martinthomson** [w3ctag/web-https#14]
The reason that some private networks have trouble acquiring certificates is not that they run 1918 addresses, as the current text implies.

Running in a private network might make the validation process a little trickier, but CAs provide plenty of good options that don't require direct access to the host running the service from the public Internet.  The problem more likely to be that they operate using names that would not be valid in the global scope, such as 'http://home./'; with a large number of systems and people who have come to rely on those names.

**Comment by mnot** [comment]
What was meant was that when an IP address -- rather than a hostname -- is used to access a private address, you can't get a cert for it (as per the baseline requirements 9.2.1). 

This is typical for non-geek home / small networking, where running DNS infrastructure is too heavyweight for most users, as is getting certs.

**Comment by mnot** [comment]
Good enough?

**Comment by martinthomson** [comment]
Thanks.
